replicas: 1

metadata:
  labels:
    tier: frontend
    app: hello-world-app
    env: dev

containers:
  image: 134448505602.dkr.ecr.ap-south-1.amazonaws.com/hello-world-app
  tag: "v1.1.10"
  ports:
    containerPort: 8080