apiVersion: apps/v1 
kind: Deployment
metadata:
  name: {{ .Values.metadata.labels.app }}-deployment
  labels: 
    {{- include "hello-world.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      {{- include "hello-world.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "hello-world.labels" . | nindent 8 }}
    spec:
      containers:
        - image: {{ .Values.containers.image }}:{{ .Values.containers.tag }}
          name: {{ .Values.metadata.labels.app }}-container
          imagePullPolicy: Always
          ports:
          - containerPort: {{ .Values.containers.ports.containerPort }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1