apiVersion: v1
kind: Service
metadata:
  name: {{ .values.metadata.labels.app }}-service
  labels:
    {{ - include "hello-world.labels" . | nindent 4 }}
spec:
  selector:
      {{ - include "hello-world.matchlabels" . | nindent 6 }}
  ports:
    - port: {{ .Values.containers.ports.containerPort }}
      targetPort: {{ .Values.containers.ports.containerPort }}
  type: NodePort
